name: Publish Versioned Docker Image

on:
  release:
    types: [published]

jobs:
  buildDockerImage:
    name: Push Docker image to Container Registry
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: ./
        tags: |
          ghcr.io/etspaceman/graalvm-ce-base:${{ github.event.release.tag_name }}
        push: true
